Fix: lttng-sessiond: variable 'ret' is used uninitialized
This fixes the following clang warnings:
    CC       trace-kernel.o
  trace-kernel.c:599:7: error: variable 'ret' is used uninitialized whenever switch case is taken [-Werror,-Wsometimes-uninitialized]
          case LTTNG_EVENT_RULE_TYPE_SYSCALL:
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  trace-kernel.c:618:9: note: uninitialized use occurs here
          return ret;
               	 ^~~
  trace-kernel.c:594:7: error: variable 'ret' is used uninitialized whenever switch case is taken [-Werror,-Wsometimes-uninitialized]
          case LTTNG_EVENT_RULE_TYPE_TRACEPOINT:
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  trace-kernel.c:618:9: note: uninitialized use occurs here
          return ret;
               	 ^~~
  trace-kernel.c:585:7: error: variable 'ret' is used uninitialized whenever switch case is taken [-Werror,-Wsometimes-uninitialized]
          case LTTNG_EVENT_RULE_TYPE_KRETPROBE:
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  trace-kernel.c:618:9: note: uninitialized use occurs here
          return ret;
               	 ^~~
  trace-kernel.c:571:7: error: variable 'ret' is used uninitialized whenever switch case is taken [-Werror,-Wsometimes-uninitialized]
          case LTTNG_EVENT_RULE_TYPE_KPROBE:
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
  trace-kernel.c:618:9: note: uninitialized use occurs here
          return ret;
               	 ^~~
  trace-kernel.c:562:2: note: variable 'ret' is declared here
          enum lttng_error_code ret;
          ^
  4 errors generated.
  Makefile:746: recipe for target 'trace-kernel.o' failed
  make: *** [trace-kernel.o] Error 1

Signed-off-by: Francis Deslauriers <francis.deslauriers@efficios.com>
Change-Id: I9e72c1ed5458fee9e62f5895b66f4da0da80fb7b